project:
  type: website
  render:
    - "*.qmd"
    - presentations/*.qmd
  output-dir: docs



website:
  title: "Rowan Norenberg"
  navbar:
    right: 
      - href: index.html 
      - text: "About Me"
        href: index.html
      - text: "Linguistics"
        menu: 
         - text: "CLIL Presentation"
           href: Presentation.html
         - text: "CLIL"
           href: Project3.html
      - text: "Data Viz"
        menu: 
         - text: "Tidy Tuesday - D&D"
           href: TidyTuesdayD&amp;D.html
         - text: "Tidy Tuesday - Shakespeare"
           href: tidyv3.html
         - text: "Content and Language Integrated-Learning and Cognition"
           href: Project3.html
         - text: "Data Ethics - OkCupid"
           href: project4.html
         - text: "SQL - Stanford Open Policing Project"
           href: project5.html



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

