project:
  type: website
  output-dir: docs


website:
  title: "Rowan Norenberg"
  navbar:
    right: 
      - href: index.html 
      - text: "About Me"
        href: about.html
      - text: "Data Viz"
        menu: 
         - text: "Tidy Tuesday - D&D Monsters"
           href: tidyv1.html
         - text: "Tidy Tuesday - D&D Spells"
           href: tidyv2.html



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

